@startuml

skinparam monochrome true
title th_battery \n

start

while ()
  :comDemarree?;
  :wait 500ms;
  :level = (MessageBattery*)robot.Write(ComRobot::GetBattery());
  :msgToMon!level;
  note 
    method WriteInQueue
    in task.cpp
  endnote
  
endwhile
stop

@enduml