@startuml th_com_robot

skinparam monochrome true

start

while( )
    :openComRobot?comRobotEventFlag;
    if (comRobotEventFlag) then (OPEN)
    :err = robot.Open();
        if (err) then (robot_ok)
        :msgSend = new Message(MESSAGE_ANSWER_ACK);
        :comRobotStartEvent!START;
        else
            :msgSend = new Message(MESSAGE_ANSWER_NACK);
        endif
    else (CLOSE)
        :comRobotStartEvent!STOP;
        :robot.Close();
        :msgSend = new Message(MESSAGE_COM_CLOSED);
        
        'Check message type
    endif
    :msgToMon!msgSend;
endwhile
stop
@enduml
