@startuml th_calibration

skinparam monochrome true

start

while ( )
    :findArena?;

    :Envoi!STOP;
    note : Event pour mettre en pause / reprendre le flux d'images

    :img = Camera.Grab();

    :arenaLoc = Img::SearchArena(img);

    if (arena) then (null)
        :msg = new Message(MESSAGE_ANSWER_NACK);
        :msgToMon!msg;
    else
        :img = Img::DrawArena(arena);
        :msgToMon!img;
        :arenaValid()?val;
        if(val) then (OK)
            :arena = arenaLoc;
        else (KO)
            :arena = null;
        endif
    endif

    :Envoi!RESUME;
    
endwhile

stop

@enduml
