@startuml th_watchdog

skinparam monochrome true

'Modifier conception pour retirer stop signal
'Inutile (Semaphore bloquant tant que pas d'utilité de cette tâche)
start

while( )

:eventWD?START;
note right
    Blocage tant que eventWD!=START
    Synchro sur sémaphore 
    (try pour ne pas décrémenter, décrementer dans th_move pour stopper)
end note

:ComRobot::Write(DMB_RELOAD_WD);

:Wait 1s;

endwhile


stop

@enduml
